GET https://jsonplaceholder.typicode.com/todos/1
accept: application/json

###

POST https://reqres.in/api/users
accept: application/json
Content-type:application/json

{
    "name": "morpheus",
    "job": "leader",
    "array": ["a", "b", "c"],
    "object_ugly_closing": {
      "some_key": "some_value"
  }
}

###

POST https://reqres.in/api/users
accept: application/json
Content-Type: application/json

{
    "userid" : "{{$uuid}}",
    "time" : "{{$timestamp}}",
    "randomValue": "{{$randomInt}}",
    "name": "morpheus",
    "job": "leader",
    "array": ["a", "b", "c"],
    "object_ugly_closing": {
      "some_key": "some_value"
  }
}
