//              # -> fuzzy_sorter
//              . -> set_root
//              / -> fuzzy_finder
//              < -> prev_source
//  <2-leftmouse> -> open
//           <bs> -> navigate_up
//          <c-b> -> scroll_preview
//          <c-f> -> scroll_preview
//          <c-x> -> clear_filter
//           <cr> -> open
//          <esc> -> cancel
//          <tab> -> open
//              > -> next_source
//              ? -> show_help
//              A -> add_directory
//              C -> close_node
//              D -> fuzzy_finder_directory
//              H -> toggle_hidden
//              O -> Open with System Application
//              P -> toggle_preview
//              R -> refresh
//              S -> open_split
//              Y -> Copy Path to Clipboard
//             [g -> prev_git_modified
//             ]g -> next_git_modified
//              a -> add
//              c -> copy
//              d -> delete
//              e -> toggle_auto_expand_width
//              f -> filter_on_submit
//              h -> close_node
//              i -> show_file_details
//              l -> open
//              m -> move
//              o -> open
//              p -> paste_from_clipboard
//              q -> close_window
//              r -> rename
//              s -> open_vsplit
//              t -> open_tabnew
//              w -> open_with_window_picker
//              x -> cut_to_clipboard
//              y -> copy_to_clipboard
//              z -> close_all_nodes
