### 

GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Accept: application/json


### 

POST https://reqres.in/api/users HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "array": [
    "a",
    "b",
    "c"
  ],
  "job": "leader",
  "name": "morpheus",
  "object_ugly_closing": {
    "some_key": "some_value"
  }
}


### 

POST https://reqres.in/api/users HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "array": [
    "a",
    "b",
    "c"
  ],
  "job": "leader",
  "name": "morpheus",
  "object_ugly_closing": {
    "some_key": "some_value"
  },
  "randomValue": "{{$randomInt}}",
  "time": "{{$timestamp}}",
  "userid": "{{$uuid}}"
}
