### 

GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Accept: application/json


### 测试文件上传 - httpbin

POST https://httpbin.org/post HTTP/1.1
Content-Type: multipart/form-data; boundary={{$timestamp}}

--{{$timestamp}}
Content-Disposition: form-data; name="description"

test file upload from kulala
--{{$timestamp}}
Content-Disposition: form-data; name="file"; filename="test.http"
Content-Type: application/octet-stream

< ./test.http
--{{$timestamp}}--
