return {
  -- {
  --   "saghen/blink.cmp",
  --   version = "0.*",
  --   dependencies = {
  --     -- add source
  --     "hrsh7th/cmp-cmdline",
  --     "octaltree/cmp-look",
  --     "hrsh7th/cmp-emoji",
  --     "hrsh7th/cmp-calc",
  --   },
  --   sources = {
  --     completion = {
  --       -- remember to enable your providers here
  --       enabled_providers = { "lsp", "path", "snippets", "buffer", "cmp-look", "cmp-emoji", "cmp-calc" },
  --     },
  --
  --     providers = {
  --       -- create provider
  --       -- digraphs = {
  --       --   name = "digraphs", -- IMPORTANT: use the same name as you would for nvim-cmp
  --       --   module = "blink.compat.source",
  --       --
  --       --   -- all blink.cmp source config options work as normal:
  --       --   score_offset = -3,
  --       --
  --       --   opts = {
  --       --     -- this table is passed directly to the proxied completion source
  --       --     -- as the `option` field in nvim-cmp's source config
  --       --
  --       --     -- this is an option from cmp-digraphs
  --       --     cache_digraphs_on_start = true,
  --       --   },
  --       -- },
  --     },
  --   },
  -- },
}
