return {
  -- "hedyhli/outline.nvim",
  "simrat39/symbols-outline.nvim",
  keys = { { "<A-o>", "<cmd>SymbolsOutline<cr>", desc = "Toggle Outline" } },

  opts = {
    position = "left",
    width = 35,
    keymaps = {
      close = { "<Esc>", "q" },
      goto_location = "o",
      focus_location = { "<Cr>", "<Tab>" },
    },
    symbols = {
      File = { icon = "󰈔", hl = "Identifier" },
      Module = { icon = "󰆧", hl = "Include" },
      Namespace = { icon = "󰅪", hl = "Include" },
      Package = { icon = "󰏗", hl = "Include" },
      Class = { icon = "", hl = "Type" },
      Method = { icon = "ƒ", hl = "Function" },
      Property = { icon = "", hl = "Identifier" },
      Field = { icon = "󰆨", hl = "Identifier" },
      Constructor = { icon = "", hl = "Special" },
      Enum = { icon = "ℰ", hl = "Type" },
      Interface = { icon = "󰜰", hl = "Type" },
      Function = { icon = "", hl = "Function" },
      Variable = { icon = "", hl = "Constant" },
      Constant = { icon = "", hl = "Constant" },
      String = { icon = "", hl = "String" },
      Number = { icon = "#", hl = "Number" },
      Boolean = { icon = "⊨", hl = "Boolean" },
      Array = { icon = "󰅪", hl = "Constant" },
      Object = { icon = "⦿", hl = "Type" },
      Key = { icon = "", hl = "Type" },
      Null = { icon = "NULL", hl = "Type" },
      EnumMember = { icon = "", hl = "Identifier" },
      Struct = { icon = "", hl = "Structure" },
      Event = { icon = "", hl = "Type" },
      Operator = { icon = "+", hl = "Identifier" },
      TypeParameter = { icon = "𝙏", hl = "Identifier" },
      Component = { icon = "󰅴", hl = "Function" },
      Fragment = { icon = "󰅴", hl = "Constant" },
      TypeAlias = { icon = " ", hl = "Type" },
      Parameter = { icon = " ", hl = "Identifier" },
      StaticMethod = { icon = " ", hl = "Function" },
      Macro = { icon = " ", hl = "Function" },
    },
  },
  -- opts = {
  --   outline_window = {
  --     position = "left",
  --     width = 35,
  --   },
  --   keymaps = {
  --     peek_location = "<Tab>",
  --     goto_location = "<Cr>",
  --     goto_and_close = "o",
  --   },
  --   symbols = {
  --     icons = {
  --       File = { icon = "󰈔", hl = "Identifier" },
  --       Module = { icon = "󰆧", hl = "Include" },
  --       Namespace = { icon = "󰅪", hl = "Include" },
  --       Package = { icon = "󰏗", hl = "Include" },
  --       Class = { icon = "", hl = "Type" },
  --       Method = { icon = "ƒ", hl = "Function" },
  --       Property = { icon = "", hl = "Identifier" },
  --       Field = { icon = "󰆨", hl = "Identifier" },
  --       Constructor = { icon = "", hl = "Special" },
  --       Enum = { icon = "ℰ", hl = "Type" },
  --       Interface = { icon = "󰜰", hl = "Type" },
  --       Function = { icon = "", hl = "Function" },
  --       Variable = { icon = "", hl = "Constant" },
  --       Constant = { icon = "", hl = "Constant" },
  --       String = { icon = "", hl = "String" },
  --       Number = { icon = "#", hl = "Number" },
  --       Boolean = { icon = "⊨", hl = "Boolean" },
  --       Array = { icon = "󰅪", hl = "Constant" },
  --       Object = { icon = "⦿", hl = "Type" },
  --       Key = { icon = "", hl = "Type" },
  --       Null = { icon = "NULL", hl = "Type" },
  --       EnumMember = { icon = "", hl = "Identifier" },
  --       Struct = { icon = "", hl = "Structure" },
  --       Event = { icon = "", hl = "Type" },
  --       Operator = { icon = "+", hl = "Identifier" },
  --       TypeParameter = { icon = "𝙏", hl = "Identifier" },
  --       Component = { icon = "󰅴", hl = "Function" },
  --       Fragment = { icon = "󰅴", hl = "Constant" },
  --       TypeAlias = { icon = " ", hl = "Type" },
  --       Parameter = { icon = " ", hl = "Identifier" },
  --       StaticMethod = { icon = " ", hl = "Function" },
  --       Macro = { icon = " ", hl = "Function" },
  --     },
  --   },
  -- },
}
