return {
  -- "ahmedkhalf/project.nvim",
  -- opts = {
  --   manual_mode = true,
  -- },
  -- event = "VeryLazy",
  -- config = function()
  --   require("project_nvim").setup({
  --     manual_mode = false,
  --     detection_methods = { "lsp", "pattern" },
  --     patterns = { ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json", "squirrel.yaml" },
  --     ignore_lsp = {},
  --     exclude_dirs = {},
  --     show_hidden = false,
  --     silent_chdir = true,
  --     scope_chdir = "global",
  --
  --     -- datapath = vim.fn.stdpath("data") .. "~/.config/nvim/projects/",
  --   })
  --   -- require("lazyvim.util").on_load("telescope.nvim", function()
  --   --   require("telescope").load_extension("projects")
  --   -- end)
  -- end,
}
