return {
	"miversen33/sunglasses.nvim",
	enabled = false,
	event = "UIEnter",
	config = function()
		local sunglasses_options = {
			filter_percent = 0.65,
			filter_type = "NOSYNTAX",
			refresh_timer = 5,
			excluded_filetypes = {
				"dashboard",
				"lspsagafinder",
				"packer",
				"checkhealth",
				"mason",
				"NvimTree",
				"neo-tree",
				"plugin",
				"lazy",
				"TelescopePrompt",
				"alpha",
				"toggleterm",
				"sagafinder",
				"better_term",
				"fugitiveblame",
				"starter",
				"NeogitPopup",
				"NeogitStatus",
				"DiffviewFiles",
				"DiffviewFileHistory",
				"DressingInput",
				"spectre_panel",
				"zsh",
				"registers",
				"startuptime",
				"OverseerList",
				"Navbuddy",
				"noice",
				"notify",
				"saga_codeaction",
				"sagarename",
			},
		}

		require("sunglasses").setup(sunglasses_options)
	end,
}
