return {
  {
    "Goose97/timber.nvim",
    -- version = "*",
    -- event = "VeryLazy",
    event = { "InsertEnter" },
    config = function()
      require("timber").setup({
        keymaps = {
          insert_log_below = "<leader>pb",
        },
        default_keymaps_enabled = false,
        log_templates = {
          default = {
            vue = [[console.log("%log_target", %log_target)]],
            javascript = [[console.log("%log_target", %log_target);]],
            typescript = [[console.log("%log_target", %log_target);]],
            jsx = [[console.log("%log_target", %log_target);]],
            tsx = [[console.log("%log_target", %log_target);]],
            lua = [[print("%log_target", %log_target)]],
            ruby = [[puts("%log_target #{%log_target}")]],
            elixir = [[IO.inspect(%log_target, label: "%log_target")]],
            go = [[log.Printf("%log_target: %v\n", %log_target)]],
            rust = [[println!("%log_target: {:#?}", %log_target);]],
            python = [[print(f"{%log_target=}")]],
            c = [[printf("%log_target: %s\n", %log_target);]],
            cpp = [[std::cout << "%log_target: " << %log_target << std::endl;]],
            java = [[System.out.println("%log_target: " + %log_target);]],
            c_sharp = [[Console.WriteLine($"%log_target: {%log_target}");]],
            odin = [[fmt.printfln("%log_target: %v", %log_target)]],
            swift = [[print("%log_target:", %log_target)]],
            kotlin = [[println("%log_target: ${%log_target}")]],
          },
          plain = {
            vue = [[console.log("%insert_cursor")]],
            javascript = [[console.log("%insert_cursor")]],
            typescript = [[console.log("%insert_cursor")]],
            jsx = [[console.log("%insert_cursor")]],
            tsx = [[console.log("%insert_cursor")]],
            lua = [[print("%insert_cursor")]],
            ruby = [[puts("%insert_cursor")]],
            elixir = [[IO.puts(%insert_cursor)]],
            go = [[log.Printf("%insert_cursor")]],
            rust = [[println!("%insert_cursor");]],
            python = [[print(f"%insert_cursor")]],
            c = [[printf("%insert_cursor \n");]],
            cpp = [[std::cout << "%insert_cursor" << std::endl;]],
            java = [[System.out.println("%insert_cursor");]],
            c_sharp = [[Console.WriteLine("%insert_cursor");]],
            odin = [[fmt.println("%insert_cursor")]],
            swift = [[print("%insert_cursor")]],
            kotlin = [[println("%insert_cursor")]],
          },
        },
      })
    end,
  },
}
